version: '3.8'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./BACKEND:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && nodemon index.js"